version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=https://www.practicehero.co.uk
      - NEXT_PUBLIC_DOMAIN=practicehero.co.uk
      - NEXT_PUBLIC_SITE_NAME=Practice Hero
      - NEXT_PUBLIC_SITE_DESCRIPTION=AI-powered EHR summarization tool that helps GPs prepare for consultations
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
