[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[phases.cache]
paths = [
  "node_modules/.pnpm",
  ".next/cache"
]
